name: Lint

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: black
                uses: psf/black@22.10.0

            -   name: ruff
                uses: astral-sh/ruff-action@v0.14.0
                with:
                    args: 'format --check'
